name: build
on: [push]
jobs:
  run:
    name: Build
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        ocaml-version: [ '4.05.0' ]
        operating-system: [ubuntu-latest]
        # operating-system: [macos-latest, ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@master
    - uses: avsm/setup-ocaml@master
      with:
        ocaml-version: ${{ matrix.ocaml-version }}
    - run: opam pin -n .
    - run: opam depext -yt imgui imgui-sdl-opengl3 conf-sdl2
    - run: opam install -t . --deps-only
    - run: opam exec -- dune build
    - run: opam exec -- dune runtest
